DROP TABLE timecard;

create table timecard (
	id int identity(1,1),
	user_name VARCHAR(50),
	project VARCHAR(50),
	start_datetime DATETIME,
	end_datetime DATETIME,
	notes TEXT,
	constraint pk_timecard primary key (id)
);

insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-09 06:44', '2017-10-09 10:21', 'Duis mattis egestas metus. Aenean fermentum.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-09 11:19', '2017-10-09 14:49', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-10 07:59', '2017-10-10 10:15', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2016-10-10 10:39', '2017-10-10 14:48', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-10 15:54', '2016-10-10 19:06', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-11 09:00', '2016-10-11 10:04', 'Nulla ut erat id mauris vulputate elementum.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2016-10-11 11:19', '2017-10-11 11:49', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-11 12:30', '2017-10-11 16:33', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-12 13:17', '2017-10-12 14:45', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-13 08:36', '2017-10-13 16:57', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-16 08:28', '2017-10-16 11:50', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-16 13:28', '2017-10-16 15:07', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-16 17:57', '2016-10-16 18:28', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-17 09:42', '2017-10-17 12:10', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-17 14:27', '2017-10-17 19:35', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2016-10-18 19:32', '2017-10-18 15:27', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-18 16:13', '2017-10-18 16:52', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2016-10-19 09:53', '2017-10-19 13:14', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2017-10-19 14:02:18', '2017-10-19 17:42:32', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.');
insert into TIMECARD (user_name, project, start_datetime, end_datetime, notes) values ('john@abc.com', 'Online E-Card Generator', '2016-10-20 10:41:12', '2016-10-20 18:07:54', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');																										